# Generated by Django 3.2.13 on 2022-06-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=30)),
                ('case', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=5)),
                ('declension', models.CharField(max_length=15)),
            ],
        ),
    ]
