# Generated by Django 3.2.13 on 2022-06-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_question_api_questio_declens_b50df6_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='points_multiplier',
            field=models.IntegerField(default=1),
        ),
    ]
