# Generated by Django 3.2.13 on 2022-06-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userextension_points_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='points_insurance',
            field=models.IntegerField(default=1),
        ),
    ]
