# Generated by Django 3.2.13 on 2022-06-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_userextension_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='times_incorrect',
            field=models.IntegerField(default=0),
        ),
    ]
