# Generated by Django 3.2.13 on 2022-06-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_question_times_incorrect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
            ],
        ),
    ]
