# Generated by Django 3.2.13 on 2022-06-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='comp_insurance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userextension',
            name='comp_multiplier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userextension',
            name='comp_points',
            field=models.IntegerField(default=0),
        ),
    ]
