# Generated by Django 3.2.13 on 2022-06-30 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220628_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['-time_start']},
        ),
    ]
