# Generated by Django 3.2.13 on 2022-06-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_competition_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='time_start',
            field=models.TimeField(auto_now=True),
        ),
    ]
