# Generated by Django 3.2.13 on 2022-07-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_userextension_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='is_competing',
            field=models.BooleanField(default=False),
        ),
    ]
