# Generated by Django 3.2.13 on 2022-07-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_userextension_is_competing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rumble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time_start', models.TimeField(auto_now=True)),
                ('time_end', models.TimeField()),
            ],
            options={
                'ordering': ['-time_start'],
            },
        ),
    ]
