# Generated by Django 3.2.13 on 2022-07-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rumble'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rumble',
            name='time_end',
        ),
        migrations.AddField(
            model_name='rumble',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
